permalink:           pretty
relative_permalinks: true

# Setup
title:               Jungle Biome
tagline:             'Welcome to the Jungle'
description:         'Description of a Jungle Biome'
url:                 http://brian-nelson.github.io/EBNBiome
baseurl:             'http://brian-nelson.github.io/EBNBiome'
paginate:            5

# About/contact
author:
  name:              E. Nelson

# Custom vars
version:             1.0.0
